name: github-action-training-push

on: 
    push:
        braches:
        - master

env:
    AZURE_PUBLISH_PATH: "./publish"
    SOLUTION_PATH: "./GitHubActionsTraining.sln"

jobs:
    publish-proj:
        runs-on: ubuntu-latest
        steps:
          - name: Fecth code
            uses: actions/checkout@v3

          - name: Setup node
            uses: actions/setup-node@v3

          - name: Check node version
            run: node -v

          - name: Restore project
            run: dotnet restore "${{env.SOLUTION_PATH}}"
            
          - name: Build project
            run: dotnet build "${{env.SOLUTION_PATH}} --no-restore"
            
          - name: Publish project
            run: dotnet publish "${{env.SOLUTION_PATH}}" --output "${{env.AZURE_PUBLISH_PATH}}" --no-biuld