name: github-action-training-push

on: [push]

jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fecth code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        run: node -v

      - name: Check node version
        run: node -v

      - name: Build project
        run: dotnet build
