name: github-action-training-push

on: 
    push:
        branches:
        - master

env:
    AZURE_PUBLISH_PATH: "./publish"
    SOLUTION_PATH: "./GitHubActionsTraining.sln"
    TEST_SOLUTION_PATH: "./GitHubActionsTraining.Tests/GitHubActionsTraining.Tests.csproj"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Fecth code
            uses: actions/checkout@v3

          - name: Setup .Net
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: '6.0.x'

          - name: Restore project
            run: dotnet restore "${{env.SOLUTION_PATH}}"
            
          - name: Build project
            run: dotnet build "${{env.SOLUTION_PATH}}" --configuration Release --no-restore

          - name: Test project
            run: dotnet test "${{env.TEST_SOLUTION_PATH}}" --configuration Release
            
          - name: Publish project
            run: dotnet publish "${{env.SOLUTION_PATH}}" --configuration Release --output "${{env.AZURE_PUBLISH_PATH}}" --no-build
        
          - name: Deploy
            uses: azure/webapps-deploy@v3
            with:
                app-name: "time-service-test"
                publish-profile: "${{secrets.PUBLISH_PROFILE}}"
                package: "${{env.AZURE_PUBLISH_PATH}}"
